### ISSUE TITLE
job_latency breaks with rails 7.1.4.1

### ISSUE THREAD

**Issue by danteskin** [Fullscript/yabeda-activejob#15]
After update rails from 7.1.3.1 to 7.1.4.1 
after updating the job_latency method, the "argument out of range" error broke
Link to the rails updates that led to the error
https://github.com/rails/rails/commit/de779f2bf7f8537ad7097f2568e1936daedba84f

backtrace
```
    argument out of range
    /usr/local/lib/ruby/3.3.0/time.rb:271:in `local'
    /usr/local/lib/ruby/3.3.0/time.rb:271:in `make_time'
    /usr/local/lib/ruby/3.3.0/time.rb:386:in `parse'
    /app/vendor/bundle/ruby/3.3.0/gems/yabeda-activejob-0.5.0/lib/yabeda/activejob.rb:100:in `job_latency'
    /app/vendor/bundle/ruby/3.3.0/gems/yabeda-activejob-0.5.0/lib/yabeda/activejob.rb:73:in `block (2 levels) in install!'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/fanout.rb:137:in `block in finish'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/fanout.rb:26:in `block in iterate_guarding_exceptions'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/fanout.rb:25:in `each'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/fanout.rb:25:in `iterate_guarding_exceptions'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/fanout.rb:125:in `each'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/fanout.rb:136:in `finish'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/fanout.rb:262:in `block in finish_with_values'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/fanout.rb:26:in `block in iterate_guarding_exceptions'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/fanout.rb:25:in `each'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/fanout.rb:25:in `iterate_guarding_exceptions'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/fanout.rb:261:in `finish_with_values'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/fanout.rb:254:in `finish'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/instrumenter.rb:64:in `instrument'
    /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications.rb:206:in `instrument'
    ```

**Comment by andrewmarkle** [comment]
Thanks @danteskin it's closed by https://github.com/Fullscript/yabeda-activejob/pull/12
